//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BazaFilmów.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oceny
    {
        public string Id_usera { get; set; }
        public int Id_filmu { get; set; }
        public int ocena { get; set; }
    
        public virtual Filmy Filmy { get; set; }
    }
}
